// Generated by CoffeeScript 1.6.3
(function() {
  var PlayCommand, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PlayCommand = (function(_super) {
    __extends(PlayCommand, _super);

    function PlayCommand() {
      _ref = PlayCommand.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PlayCommand.prototype.execute = function(channel_id) {
      return this.echo("Play channel " + channel_id);
    };

    return PlayCommand;

  })(window.CommandBase);

  (new PlayCommand("play", "Format: play <channel_id>. Play a channel.")).register();

}).call(this);

/*
//@ sourceMappingURL=command.play.map
*/
