// Generated by CoffeeScript 1.6.3
(function() {
  var LoginCommand, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  LoginCommand = (function(_super) {
    __extends(LoginCommand, _super);

    function LoginCommand() {
      _ref = LoginCommand.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    LoginCommand.prototype.execute = function() {
      return window.T.login_begin();
    };

    return LoginCommand;

  })(window.CommandBase);

  (new LoginCommand("login", "Login to douban.fm")).register();

}).call(this);

/*
//@ sourceMappingURL=command.login.map
*/
