// Generated by CoffeeScript 1.6.3
(function() {
  var NextCommand, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  NextCommand = (function(_super) {
    __extends(NextCommand, _super);

    function NextCommand() {
      _ref = NextCommand.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    NextCommand.prototype.execute = function() {
      return window.DoubanFM.next();
    };

    return NextCommand;

  })(window.CommandBase);

  (new NextCommand("next", "Play next song.")).register();

}).call(this);

/*
//@ sourceMappingURL=command.next.map
*/
