// Generated by CoffeeScript 1.6.3
(function() {
  var StopCommand, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  StopCommand = (function(_super) {
    __extends(StopCommand, _super);

    function StopCommand() {
      _ref = StopCommand.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    StopCommand.prototype.execute = function() {
      return window.DoubanFM.stop();
    };

    return StopCommand;

  })(window.CommandBase);

  (new StopCommand("stop", "Stop playing.")).register();

}).call(this);

/*
//@ sourceMappingURL=command.stop.map
*/
