// Generated by CoffeeScript 1.6.3
(function() {
  var ChannelCommand, channel, proxy, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  proxy = "https://jsonpwrapper.appspot.com/?callback=?";

  channel = "http://www.douban.com/j/app/radio/channels";

  String.prototype.width = function() {
    var c, i, len, width, _i, _len;
    len = this.length;
    width = 0;
    for (c = _i = 0, _len = this.length; _i < _len; c = ++_i) {
      i = this[c];
      if (this.charCodeAt(i) || this.charCodeAt(i) > 126) {
        width += 2;
      } else {
        width++;
      }
    }
    return width;
  };

  ChannelCommand = (function(_super) {
    __extends(ChannelCommand, _super);

    function ChannelCommand() {
      _ref = ChannelCommand.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ChannelCommand.prototype.on_data = function(data) {
      var channels, delta, i, json, jsonp, line, max_name_length, name, name_per_line, parsed, space, x, _i, _j, _len, _len1;
      window.T.resume();
      x = $("" + data.responseText + "");
      jsonp = x[5].innerHTML;
      json = jsonp.substring(jsonp.indexOf('(') + 1, jsonp.lastIndexOf(')'));
      parsed = $.parseJSON(json);
      channels = parsed.channels;
      if (channels == null) {
        this.echo(parsed.error);
      }
      max_name_length = 0;
      for (_i = 0, _len = channels.length; _i < _len; _i++) {
        channel = channels[_i];
        max_name_length = Math.max(channel.name.width(), max_name_length);
      }
      name_per_line = Math.floor(80 / max_name_length);
      line = "";
      space = 2;
      for (i = _j = 0, _len1 = channels.length; _j < _len1; i = ++_j) {
        channel = channels[i];
        if (i !== 0 && i % name_per_line === 0) {
          this.echo(line);
          line = "";
        }
        name = channel.name;
        delta = max_name_length + space - name.width();
        line += channel.name + Array(Math.floor(delta / 4)).join("\t");
      }
      this.echo(line);
    };

    ChannelCommand.prototype.on_error = function() {
      window.T.resume();
      this.echo("Error, try again later");
    };

    ChannelCommand.prototype.execute = function() {
      var _this = this;
      this.echo("Requesting...");
      window.T.pause();
      $.ajax({
        type: 'GET',
        dateType: 'jsonp',
        data: {
          'url': channel
        },
        url: proxy,
        xhrFields: {
          withCredentials: false
        },
        success: function(data) {
          return _this.on_data(data);
        },
        error: function() {
          this.on_error;
        }
      });
    };

    return ChannelCommand;

  })(window.CommandBase);

  (new ChannelCommand("channel", "Show channel list")).register();

}).call(this);

/*
//@ sourceMappingURL=command.channel.map
*/
