// Generated by CoffeeScript 1.6.3
(function() {
  var MuteCommand, VolCommand, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MuteCommand = (function(_super) {
    __extends(MuteCommand, _super);

    function MuteCommand() {
      _ref = MuteCommand.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    MuteCommand.prototype.execute = function() {
      return window.DoubanFM.mute();
    };

    return MuteCommand;

  })(window.CommandBase);

  VolCommand = (function(_super) {
    __extends(VolCommand, _super);

    function VolCommand() {
      _ref1 = VolCommand.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    VolCommand.prototype.execute = function(vol) {
      return window.DoubanFM.setVol(vol);
    };

    return VolCommand;

  })(window.CommandBase);

  (new MuteCommand("mute", "Mute/unmute")).register();

  (new VolCommand("vol", "Format: vol <range>. Set volume. Range 0~100. Display current volume if range is not provided.")).register();

}).call(this);

/*
//@ sourceMappingURL=command.vol.map
*/
