// Generated by CoffeeScript 1.6.3
(function() {
  var LogoutCommand, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  LogoutCommand = (function(_super) {
    __extends(LogoutCommand, _super);

    function LogoutCommand() {
      _ref = LogoutCommand.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    LogoutCommand.prototype.execute = function() {
      window.DoubanFM.logout();
      window.T.echo("Logout...");
      return window.TERM.setUser(window.DoubanFM.user);
    };

    return LogoutCommand;

  })(window.CommandBase);

  (new LogoutCommand("logout", "Logout from douban.fm")).register();

}).call(this);

/*
//@ sourceMappingURL=command.logout.map
*/
