// Generated by CoffeeScript 1.6.3
(function() {
  var PrevCommand, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PrevCommand = (function(_super) {
    __extends(PrevCommand, _super);

    function PrevCommand() {
      _ref = PrevCommand.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PrevCommand.prototype.execute = function() {
      return window.DoubanFM.prev();
    };

    return PrevCommand;

  })(window.CommandBase);

  (new PrevCommand("prev", "Play previous song.")).register();

}).call(this);

/*
//@ sourceMappingURL=command.prev.map
*/
