// Generated by CoffeeScript 1.6.3
(function() {
  var TerminalProxy,
    __slice = [].slice;

  window.Pipe = new window.PipeServerClass(pipe_name);

  TerminalProxy = (function() {
    function TerminalProxy(server_pipe) {
      this.server_pipe = server_pipe;
      this.T = window.T;
      window.T = this;
    }

    TerminalProxy.prototype.echo = function() {
      var msg;
      msg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    };

    TerminalProxy.prototype.set_prompt = function() {
      var prompt;
      prompt = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    };

    TerminalProxy.prototype.pasue = function() {};

    TerminalProxy.prototype.resume = function() {};

    TerminalProxy.prototype.clear = function() {};

    return TerminalProxy;

  })();

}).call(this);

/*
//@ sourceMappingURL=Host.map
*/
