// Generated by CoffeeScript 1.6.3
(function() {
  var PipeBase, PipeClient, PipeServer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.PipeBaseClass = PipeBase = (function() {
    function PipeBase(key) {
      this.key = key;
      this.rpcMap = {};
    }

    PipeBase.prototype.registerRPC = function(name, fn) {
      return this.rpcMap[name] = fn;
    };

    PipeBase.prototype.fireRPC = function(name, args) {
      var rpc;
      rpc = {
        name: name,
        args: args
      };
      return this.post(rpc);
    };

    PipeBase.prototype.onRPC = function(msg) {
      var _base, _name;
      if (msg.name != null) {
        return typeof (_base = this.rpcMap)[_name = msg.name] === "function" ? _base[_name](msg.args) : void 0;
      }
    };

    PipeBase.prototype.dispatch = function(msg) {
      var error;
      console.log("Msg on pipe " + this.key + ":");
      console.log(msg);
      try {
        return this.onRPC(msg);
      } catch (_error) {
        error = _error;
        return console.error(error);
      }
    };

    return PipeBase;

  })();

  window.PipeClientClass = PipeClient = (function(_super) {
    __extends(PipeClient, _super);

    function PipeClient(key) {
      var _this = this;
      PipeClient.__super__.constructor.call(this, key);
      this.id = (new Date()).getTime();
      this.name = "" + key + ":" + this.id;
      console.log("Init Pipe Client " + this.name);
      this.port = chrome.runtime.connect({
        name: this.name
      });
      this.port.onMessage.addListener(function(msg) {
        return _this.dispatch(msg);
      });
    }

    PipeClient.prototype.post = function(msg) {
      var _ref;
      return (_ref = this.port) != null ? _ref.postMessage(msg) : void 0;
    };

    return PipeClient;

  })(PipeBase);

  window.PipeServerClass = PipeServer = (function(_super) {
    __extends(PipeServer, _super);

    function PipeServer(name) {
      var _this = this;
      PipeServer.__super__.constructor.call(this, name);
      this.ports = {};
      chrome.runtime.onConnect.addListener(function(port) {
        var id, key, _ref;
        console.log("Init Pipe Server " + _this.key);
        _ref = port.name.split(":"), key = _ref[0], id = _ref[1];
        if (key === _this.key) {
          console.log("Conected pipe: " + id);
          console.log(port.sender);
          _this.ports[id] = port;
          port.onMessage.addListener(function(msg) {
            return _this.dispatch(msg);
          });
          return port.onDisconnect.addListener(function(port) {
            return _this.onDisconnect(port);
          });
        }
      });
    }

    PipeServer.prototype.onDisconnect = function(port) {
      var id, key, _ref;
      console.log("OnDisconnect:");
      console.log(port);
      _ref = port.name.split(":"), key = _ref[0], id = _ref[1];
      if (id != null) {
        console.log("Pipe " + id + " disconnected");
        return delete this.ports[id];
      }
    };

    PipeServer.prototype.post = function(msg) {
      var id, port, _ref, _results;
      _ref = this.ports;
      _results = [];
      for (id in _ref) {
        port = _ref[id];
        _results.push(port != null ? port.postMessage(msg) : void 0);
      }
      return _results;
    };

    return PipeServer;

  })(PipeBase);

}).call(this);

/*
//@ sourceMappingURL=Pipe.map
*/
