// Generated by CoffeeScript 1.6.3
(function() {
  var PlayerUI;

  window.PlayerUI = PlayerUI = (function() {
    PlayerUI.prototype.init = function() {
      return this.t.echo("PlayerUI...", {});
    };

    function PlayerUI(t) {
      this.t = t;
      this.t.init_ui = this.init.bind(this);
    }

    return PlayerUI;

  })();

}).call(this);

/*
//@ sourceMappingURL=PlayerUI.map
*/
