// Generated by CoffeeScript 1.6.3
(function() {
  var Terminal, greet;

  greet = function(callback) {
    var str;
    str = "[[gb;#ffffff;#000]CatX.FM 猫杀电台\r\n]";
    str += "[[;#e67e22;]music provided by douban.fm]";
    return str;
  };

  Terminal = (function() {
    function Terminal() {
      this.commands = {};
    }

    Terminal.prototype.start = function(options) {
      return $('body').terminal(this.interpret, options);
    };

    Terminal.prototype.interpret = function(name, term) {
      var commands;
      commands = window.TERM.commands;
      if ((commands != null) && (commands[name] != null)) {
        commmands[name]();
      } else {
        term.echo("WTF?");
      }
    };

    Terminal.prototype.registerCommand = function(name, command) {
      return this.commands[name] = command;
    };

    return Terminal;

  })();

  if (window.TERM == null) {
    window.TERM = new Terminal();
  }

  jQuery(document).ready(function() {
    return window.TERM.start({
      prompt: '♫',
      name: 'catx.fm',
      greetings: greet,
      history: true,
      tabcompletion: true
    });
  });

}).call(this);

/*
//@ sourceMappingURL=terminal.map
*/
