// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(document).ready(function() {
    var Terminal, greet;
    greet = function(callback) {
      var str;
      str = "[[gb;#ffffff;#000]CatX.FM 猫杀电台\r\n]";
      str += "[[;#e67e22;]music provided by douban.fm]";
      return str;
    };
    Terminal = (function() {
      function Terminal(options) {
        $('body').terminal(this.interpret, options);
      }

      Terminal.prototype.interpret = function(command, term) {
        if (command === "test") {
          term.echo("Test");
        } else {
          term.echo("WTF?");
        }
      };

      return Terminal;

    })();
    return new Terminal({
      prompt: '♫',
      name: 'catx.fm',
      greetings: greet,
      history: true,
      tabcompletion: true
    });
  });

}).call(this);

/*
//@ sourceMappingURL=terminal.map
*/
