// Generated by CoffeeScript 1.6.3
(function() {
  var XHRService;

  XHRService = (function() {
    function XHRService() {}

    XHRService.prototype.encodePayload = function(payload) {
      var k, pairs, str, v;
      pairs = [];
      for (k in payload) {
        v = payload[k];
        pairs.push(k + "=" + v);
      }
      str = pairs.join("&");
      return str;
    };

    XHRService.prototype.query = function(type, url, payload, succ, err) {
      var data, xhr;
      xhr = new XMLHttpRequest();
      data = null;
      if (type === "GET") {
        url += "?" + this.encodePayload(payload);
      } else {
        data = payload;
      }
      xhr.onreadystatechange = function() {
        if (xhr.readyState === 4) {
          if (xhr.status === 200) {
            data = JSON.parse(xhr.responseText);
            return succ(data);
          } else {
            return err(xhr.status, "Error");
          }
        }
      };
      xhr.open(type, url, true);
      return xhr.send(data);
    };

    XHRService.prototype.get = function(url, data, succ, err) {
      return this.query("GET", url, data, succ, err);
    };

    XHRService.prototype.post = function(url, data, succ, err) {
      return this.query("POST", url, data, succ, err);
    };

    return XHRService;

  })();

  if (window.Service == null) {
    window.Service = new XHRService();
  }

}).call(this);

/*
//@ sourceMappingURL=XHRService.map
*/
